CREATE DATABASE COMPETITORS;
USE COMPETITORS;

DROP TABLE IF EXISTS MENU;
CREATE TABLE MENU
(
	SOURCE TEXT,
	LOCATION TEXT,
	NAME TEXT,
	DESCRIPTION TEXT,
	PRICE FLOAT,
	SECTION TEXT,
	DIETARY TEXT,
	QUANTITY_REMAINING INTEGER,
	RATING_AVERAGE FLOAT,
	RATING_COUNT INTEGER,
	TYPE_OF_MEAL TEXT,
	DATE DATETIME
);
